"""Exports Haven terrain maps as Luau data modules and provides the Python
reference of the in-game column function (TerrainWriter.luau) for previews
and fast simulator injection."""
import base64
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from noise import hash01  # noqa: E402
import haven as HV  # noqa: E402

CHUNK_B64 = 60000
SUB = ["Rock", "Rock", "Ground", "Ground", "Sand", "Rock", "Slate", "Rock", "Ground", "Limestone", "Basalt"]


def b64_chunks(raw: bytes):
    s = base64.b64encode(raw).decode()
    return [s[i:i + CHUNK_B64] for i in range(0, len(s), CHUNK_B64)]


def rle_u16(arr):
    """(count, value) pairs as uint16 LE, counts <= 65535."""
    flat = arr.reshape(-1)
    out = []
    i = 0
    n = len(flat)
    while i < n:
        v = int(flat[i])
        j = i + 1
        while j < n and int(flat[j]) == v and j - i < 65535:
            j += 1
        out.append((j - i, v))
        i = j
    return np.array(out, np.uint16).reshape(-1)


def encode(hv):
    H = np.round(hv.H * 64).astype(np.uint16)
    M = hv.M.astype(np.uint8)
    W = np.where(hv.W > hv.H, np.round(hv.W * 64), 0).astype(np.uint16)
    return H, M, W


def write_luau(hv, path):
    H, M, W = encode(hv)
    wr = rle_u16(W)
    carves = [[*a, *b, r0, r1] for a, b, r0, r1 in hv.carves]
    lines = ["-- GENERATED by toolchain/worldgen/terrain_data.py - do not edit by hand.",
             "-- Dragon Haven terrain: 8-stud heightmap (uint16 /64), material indices (uint8),",
             "-- water levels (RLE uint16 pairs count,value /64), 3D cave carves.",
             "return {",
             f"\tGrid = {HV.GRID:g},",
             f"\tExtent = {HV.EXTENT:g},",
             f"\tN = {HV.N},",
             "\tMaterials = { " + ", ".join(f'"{m}"' for m in HV.MATS) + " },",
             "\tSubMaterials = { " + ", ".join(f'"{m}"' for m in SUB) + " },",
             "\tColors = {"]
    for k, (r, g, b) in HV.TERRAIN_COLORS.items():
        lines.append(f"\t\t{k} = {{ {r}, {g}, {b} }},")
    lines.append("\t},")
    for name, raw in (("Heights", H.tobytes()), ("Mats", M.tobytes()), ("Water", wr.tobytes())):
        lines.append(f"\t{name} = {{")
        for c in b64_chunks(raw):
            lines.append(f'\t\t"{c}",')
        lines.append("\t},")
    lines.append("\tCarves = {")
    for c in carves:
        lines.append("\t\t{ " + ", ".join(f"{v:.2f}" for v in c) + " },")
    lines.append("\t},")
    lines.append("}")
    src = "\n".join(lines) + "\n"
    with open(path, "w") as f:
        f.write(src)
    return len(src)


# ------------------------------------------------------------------ reference column function
class Reference:
    """Mirror of TerrainWriter.luau sampling (bilinear heights + detail,
    dithered materials, water)."""
    def __init__(self, hv):
        self.hv = hv
        H, M, W = encode(hv)
        self.H = H.astype(np.float64) / 64
        self.M = M
        self.W = W.astype(np.float64) / 64
        self.N, self.G, self.E = HV.N, HV.GRID, HV.EXTENT

    def sample(self, X, Z):
        """X, Z arrays (voxel column centers) -> height, material index, water."""
        N, G, E = self.N, self.G, self.E
        fx = np.clip((X + E) / G, 0, N - 1.000001)
        fz = np.clip((Z + E) / G, 0, N - 1.000001)
        ix = np.floor(fx).astype(np.int64)
        iz = np.floor(fz).astype(np.int64)
        tx, tz = fx - ix, fz - iz
        H = self.H
        h00, h10, h01, h11 = H[iz, ix], H[iz, ix + 1], H[iz + 1, ix], H[iz + 1, ix + 1]
        h = (h00 * (1 - tx) + h10 * tx) * (1 - tz) + (h01 * (1 - tx) + h11 * tx) * tz
        cx = np.floor(X / 4).astype(np.int64)
        cz = np.floor(Z / 4).astype(np.int64)
        h = h + (hash01(cx, cz, 977) - 0.5) * 1.2
        # dithered material: pick a corner with probability = bilinear weight
        rnd = hash01(cx, cz, 433)
        w00 = (1 - tx) * (1 - tz)
        w10 = tx * (1 - tz)
        w01 = (1 - tx) * tz
        Mm = self.M
        m = np.where(rnd < w00, Mm[iz, ix], np.where(rnd < w00 + w10, Mm[iz, ix + 1],
                     np.where(rnd < w00 + w10 + w01, Mm[iz + 1, ix], Mm[iz + 1, ix + 1])))
        Wm = self.W
        w00v, w10v, w01v, w11v = Wm[iz, ix], Wm[iz, ix + 1], Wm[iz + 1, ix], Wm[iz + 1, ix + 1]
        allw = (w00v > 0) & (w10v > 0) & (w01v > 0) & (w11v > 0)
        anyw = np.maximum.reduce([w00v, w10v, w01v, w11v])
        wb = (w00v * (1 - tx) + w10v * tx) * (1 - tz) + (w01v * (1 - tx) + w11v * tx) * tz
        water = np.where(allw, wb, np.where(anyw > 0, anyw, 0.0))
        return h, m, water


if __name__ == "__main__":
    hv = HV.Haven().build()
    out = "/home/claude/RideADragon/src/ServerScriptService/World/HavenTerrainData.luau"
    n = write_luau(hv, out)
    print("wrote", out, f"{n / 1024:.0f} KB")


def inject_into_sim(sim, hv=None):
    """Registers the Haven terrain in the simulator as an analytic heightfield
    (exactly the in-game column function) and marks it prebuilt so the Luau
    builder skips the (slow in the simulator) voxel writing."""
    import rbx_terrain
    hv = hv or HV.Haven().build()
    ref = Reference(hv)

    def fn(x, z):
        h, m, w = ref.sample(np.array([x]), np.array([z]))
        return float(h[0]), HV.MATS[int(m[0])], float(w[0])

    st = rbx_terrain.get_store(sim)
    st.add_heightfield(fn, -HV.EXTENT, -HV.EXTENT, HV.EXTENT, HV.EXTENT, 0, float(hv.H.max()) + 8)
    sim.terrain.attrs["Prebuilt"] = "Haven"
    sim.haven = hv
    return ref
