"""Roblox Enum definitions used by the game (names and values).
Only enums/items that are known to exist in Roblox are listed."""

ENUMS = {
    "Material": {
        "Plastic": 256, "SmoothPlastic": 272, "Neon": 288, "Wood": 512, "WoodPlanks": 528,
        "Marble": 784, "Basalt": 788, "Slate": 800, "CrackedLava": 804, "Concrete": 816,
        "Limestone": 820, "Granite": 832, "Pavement": 836, "Brick": 848, "Pebble": 864,
        "Cobblestone": 880, "Rock": 896, "Sandstone": 912, "CorrodedMetal": 1040,
        "DiamondPlate": 1056, "Foil": 1072, "Metal": 1088, "Grass": 1280, "LeafyGrass": 1284,
        "Sand": 1296, "Fabric": 1312, "Snow": 1328, "Mud": 1344, "Ground": 1360, "Asphalt": 1376,
        "Salt": 1392, "Ice": 1536, "Glacier": 1552, "Glass": 1568, "ForceField": 1584,
        "Air": 1792, "Water": 2048,
        "Cardboard": 1327, "Carpet": 1329, "CeramicTiles": 1301, "ClayRoofTiles": 1302,
        "RoofShingles": 1303, "Leather": 1330, "Plaster": 1305, "Rubber": 1309,
    },
    "PartType": {"Ball": 0, "Block": 1, "Cylinder": 2, "Wedge": 3, "CornerWedge": 4},
    "MeshType": {"Head": 0, "Torso": 1, "Wedge": 2, "Sphere": 3, "Cylinder": 4, "FileMesh": 5,
                 "Brick": 6, "Prism": 7, "Pyramid": 8, "ParallelRamp": 9, "RightAngleRamp": 10,
                 "CornerWedge": 11},
    "NormalId": {"Right": 0, "Top": 1, "Back": 2, "Left": 3, "Bottom": 4, "Front": 5},
    "SurfaceType": {"Smooth": 0, "Glue": 1, "Weld": 2, "Studs": 3, "Inlet": 4, "Universal": 5,
                    "Hinge": 6, "Motor": 7, "SteppingMotor": 8, "SmoothNoOutlines": 10},
    "Font": {
        "Legacy": 0, "Arial": 1, "ArialBold": 2, "SourceSans": 3, "SourceSansBold": 4,
        "SourceSansLight": 5, "SourceSansItalic": 6, "Bodoni": 7, "Garamond": 8, "Cartoon": 9,
        "Code": 10, "Highway": 11, "SciFi": 12, "Arcade": 13, "Fantasy": 14, "Antique": 15,
        "SourceSansSemibold": 16, "Gotham": 17, "GothamMedium": 18, "GothamBold": 19,
        "GothamBlack": 20, "AmaticSC": 21, "Bangers": 22, "Creepster": 23, "DenkOne": 24,
        "Fondamento": 25, "FredokaOne": 26, "GrenzeGotisch": 27, "IndieFlower": 28,
        "JosefinSans": 29, "Jura": 30, "Kalam": 31, "LuckiestGuy": 32, "Merriweather": 33,
        "Michroma": 34, "Nunito": 35, "Oswald": 36, "PatrickHand": 37, "PermanentMarker": 38,
        "Roboto": 39, "RobotoCondensed": 40, "RobotoMono": 41, "Sarpanch": 42, "SpecialElite": 43,
        "TitilliumWeb": 44, "Ubuntu": 45, "Unknown": 100,
    },
    "FontWeight": {"Thin": 100, "ExtraLight": 200, "Light": 300, "Regular": 400, "Medium": 500,
                   "SemiBold": 600, "Bold": 700, "ExtraBold": 800, "Heavy": 900},
    "FontStyle": {"Normal": 0, "Italic": 1},
    "EasingStyle": {"Linear": 0, "Sine": 1, "Back": 2, "Quad": 3, "Quart": 4, "Quint": 5,
                    "Bounce": 6, "Elastic": 7, "Exponential": 8, "Circular": 9, "Cubic": 10},
    "EasingDirection": {"In": 0, "Out": 1, "InOut": 2},
    "SizeConstraint": {"RelativeXY": 0, "RelativeXX": 1, "RelativeYY": 2},
    "AspectType": {"FitWithinMaxSize": 0, "ScaleWithParentSize": 1},
    "DominantAxis": {"Width": 0, "Height": 1},
    "FillDirection": {"Horizontal": 0, "Vertical": 1},
    "HorizontalAlignment": {"Center": 0, "Left": 1, "Right": 2},
    "VerticalAlignment": {"Center": 0, "Top": 1, "Bottom": 2},
    "SortOrder": {"Name": 0, "Custom": 1, "LayoutOrder": 2},
    "TextXAlignment": {"Left": 0, "Right": 1, "Center": 2},
    "TextYAlignment": {"Top": 0, "Center": 1, "Bottom": 2},
    "TextTruncate": {"None": 0, "AtEnd": 1, "SplitWord": 2},
    "AutomaticSize": {"None": 0, "X": 1, "Y": 2, "XY": 3},
    "ScrollingDirection": {"X": 1, "Y": 2, "XY": 4},
    "ScrollBarInset": {"None": 0, "ScrollBar": 1, "Always": 2},
    "ElasticBehavior": {"WhenScrollable": 0, "Always": 1, "Never": 2},
    "VerticalScrollBarPosition": {"Right": 0, "Left": 1},
    "ZIndexBehavior": {"Global": 0, "Sibling": 1},
    "ApplyStrokeMode": {"Contextual": 0, "Border": 1},
    "LineJoinMode": {"Round": 0, "Bevel": 1, "Miter": 2},
    "ScaleType": {"Stretch": 0, "Slice": 1, "Tile": 2, "Fit": 3, "Crop": 4},
    "ResamplerMode": {"Default": 0, "Pixelated": 1},
    "StartCorner": {"TopLeft": 0, "TopRight": 1, "BottomLeft": 2, "BottomRight": 3},
    "ScreenInsets": {"None": 0, "DeviceSafeInsets": 1, "CoreUISafeInsets": 2, "TopbarSafeInsets": 3},
    "KeyCode": {
        **{chr(c): 97 + i for i, c in enumerate(range(ord("A"), ord("Z") + 1))},
        "Zero": 48, "One": 49, "Two": 50, "Three": 51, "Four": 52, "Five": 53, "Six": 54,
        "Seven": 55, "Eight": 56, "Nine": 57,
        "Space": 32, "Return": 13, "Escape": 27, "Backspace": 8, "Tab": 9, "Delete": 127,
        "Up": 273, "Down": 274, "Right": 275, "Left": 276,
        "LeftShift": 304, "RightShift": 303, "LeftControl": 306, "RightControl": 305,
        "LeftAlt": 308, "RightAlt": 307, "CapsLock": 301, "Backquote": 96, "Minus": 45,
        "Equals": 61, "Slash": 47, "Comma": 44, "Period": 46, "Semicolon": 59,
        "F1": 282, "F2": 283, "F3": 284, "F4": 285, "F5": 286, "F6": 287, "F7": 288, "F8": 289,
        "F9": 290, "F10": 291, "F11": 292, "F12": 293,
        "ButtonX": 1000, "ButtonY": 1001, "ButtonA": 1002, "ButtonB": 1003, "ButtonR1": 1004,
        "ButtonL1": 1005, "ButtonR2": 1006, "ButtonL2": 1007, "ButtonR3": 1008, "ButtonL3": 1009,
        "ButtonStart": 1010, "ButtonSelect": 1011, "DPadLeft": 1012, "DPadRight": 1013,
        "DPadUp": 1014, "DPadDown": 1015, "Thumbstick1": 1016, "Thumbstick2": 1017,
        "Unknown": 0,
    },
    "UserInputType": {"MouseButton1": 0, "MouseButton2": 1, "MouseButton3": 2, "MouseWheel": 3,
                      "MouseMovement": 4, "Touch": 7, "Keyboard": 8, "Focus": 9,
                      "Accelerometer": 10, "Gyro": 11, "Gamepad1": 12, "Gamepad2": 13,
                      "Gamepad3": 14, "Gamepad4": 15, "Gamepad5": 16, "Gamepad6": 17,
                      "Gamepad7": 18, "Gamepad8": 19, "TextInput": 20, "InputMethod": 21,
                      "None": 22},
    "UserInputState": {"Begin": 0, "Change": 1, "End": 2, "Cancel": 3, "None": 4},
    "MouseBehavior": {"Default": 0, "LockCenter": 1, "LockCurrentPosition": 2},
    "CreatorType": {"User": 0, "Group": 1},
    "ChatVersion": {"LegacyChatService": 0, "TextChatService": 1},
    "CameraType": {"Fixed": 0, "Attach": 1, "Watch": 2, "Track": 3, "Follow": 4, "Custom": 5,
                   "Scriptable": 6, "Orbital": 7},
    "HumanoidStateType": {"FallingDown": 0, "Running": 8, "RunningNoPhysics": 10, "Climbing": 12,
                          "StrafingNoPhysics": 11, "Ragdoll": 1, "GettingUp": 2, "Jumping": 3,
                          "Landed": 7, "Flying": 6, "Freefall": 5, "Seated": 13,
                          "PlatformStanding": 14, "Dead": 15, "Swimming": 4, "Physics": 16,
                          "None": 18},
    "RaycastFilterType": {"Exclude": 0, "Include": 1, "Blacklist": 0, "Whitelist": 1},
    "ActuatorRelativeTo": {"Attachment0": 0, "Attachment1": 1, "World": 2},
    "VelocityConstraintMode": {"Line": 0, "Plane": 1, "Vector": 2},
    "OrientationAlignmentMode": {"OneAttachment": 0, "TwoAttachment": 1},
    "PositionAlignmentMode": {"OneAttachment": 0, "TwoAttachment": 1},
    "Technology": {"Legacy": 0, "Voxel": 1, "Compatibility": 2, "ShadowMap": 3, "Future": 4},
    "RenderPriority": {"First": 0, "Input": 100, "Camera": 200, "Character": 300, "Last": 2000},
    "ProximityPromptStyle": {"Default": 0, "Custom": 1},
    "ProximityPromptExclusivity": {"OnePerButton": 0, "OneGlobally": 1, "AlwaysShow": 2},
    "ProximityPromptInputType": {"Keyboard": 0, "Gamepad": 1, "Touch": 2},
    "HighlightDepthMode": {"AlwaysOnTop": 0, "Occluded": 1},
    "StreamingIntegrityMode": {"Default": 0, "Disabled": 1, "MinimumRadiusPause": 2,
                               "PauseOutsideLoadedArea": 3},
    "StreamOutBehavior": {"Default": 0, "LowMemory": 1, "Opportunistic": 2},
    "ModelStreamingMode": {"Default": 0, "Atomic": 1, "Persistent": 2, "PersistentPerPlayer": 3,
                           "Nonatomic": 4},
    "RollOffMode": {"Inverse": 0, "Linear": 1, "LinearSquare": 2, "InverseTapered": 3},
    "ParticleOrientation": {"FacingCamera": 0, "FacingCameraWorldUp": 1, "VelocityParallel": 2,
                            "VelocityPerpendicular": 3},
    "ParticleEmitterShape": {"Box": 0, "Sphere": 1, "Cylinder": 2, "Disc": 3},
    "ParticleEmitterShapeStyle": {"Volume": 0, "Surface": 1},
    "ParticleEmitterShapeInOut": {"Outward": 0, "Inward": 1, "InAndOut": 2},
    "TextureMode": {"Stretch": 0, "Wrap": 1, "Static": 2},
    "ContextActionResult": {"Sink": 0, "Pass": 1},
    "CoreGuiType": {"PlayerList": 0, "Health": 1, "Backpack": 2, "Chat": 3, "All": 4,
                    "EmotesMenu": 5, "SelfView": 6, "Captures": 7},
    "PlaybackState": {"Begin": 0, "Delayed": 1, "Playing": 2, "Paused": 3, "Completed": 4,
                      "Cancelled": 5},
    "CollisionFidelity": {"Default": 0, "Hull": 1, "Box": 2, "PreciseConvexDecomposition": 3},
    "RenderFidelity": {"Automatic": 0, "Precise": 1, "Performance": 2},
    "ThumbnailType": {"HeadShot": 0, "AvatarBust": 1, "AvatarThumbnail": 2},
    "ThumbnailSize": {"Size48x48": 0, "Size180x180": 1, "Size420x420": 2, "Size60x60": 3,
                      "Size100x100": 4, "Size150x150": 5, "Size352x352": 6},
    "HumanoidDisplayDistanceType": {"Viewer": 0, "Subject": 1, "None": 2},
    "HumanoidRigType": {"R6": 0, "R15": 1},
    "SelectionBehavior": {"Escape": 0, "Stop": 1},
    "TweenStatus": {"Canceled": 0, "Completed": 1},
    "Platform": {"Windows": 0, "OSX": 1, "IOS": 2, "Android": 3, "XBoxOne": 4, "PS4": 5,
                 "None": 19},
    "DevCameraOcclusionMode": {"Zoom": 0, "Invisicam": 1},
    "DevComputerMovementMode": {"UserChoice": 0, "KeyboardMouse": 1, "ClickToMove": 2,
                                "Scriptable": 3},
    "DevTouchMovementMode": {"UserChoice": 0, "Thumbstick": 1, "DPad": 2, "Thumbpad": 3,
                             "ClickToMove": 4, "Scriptable": 5, "DynamicThumbstick": 6},
    "ExplosionType": {"NoCraters": 0, "Craters": 1},
    "ReverbType": {"NoReverb": 0, "GenericReverb": 1, "Forest": 21, "Mountains": 18,
                   "Plain": 19, "Cave": 8},
    "BorderMode": {"Outline": 0, "Middle": 1, "Inset": 2},
    "SurfaceGuiSizingMode": {"FixedSize": 0, "PixelsPerStud": 1},
    "ProductPurchaseDecision": {"NotProcessedYet": 0, "PurchaseGranted": 1},
    "BulkMoveMode": {"FireAllEvents": 0, "FireCFrameChanged": 1},
    "AlphaMode": {"Overlay": 0, "Transparency": 1},
    "ConnectionState": {"Connected": 0, "Disconnected": 1},
    "SignalBehavior": {"Default": 0, "Immediate": 1, "Deferred": 2, "AncestryDeferred": 3},
    "Limb": {"Head": 0, "Torso": 1, "LeftArm": 2, "RightArm": 3, "LeftLeg": 4, "RightLeg": 5,
             "Unknown": 6},
    "WeldConstraintPreserve": {"All": 0, "None": 1, "Touching": 2},
    "AnimationPriority": {"Idle": 0, "Movement": 1, "Action": 2, "Action2": 3, "Action3": 4,
                          "Action4": 5, "Core": 1000},
    "InfoType": {"Asset": 0, "Product": 1, "GamePass": 2, "Subscription": 3, "Bundle": 4},
    "TeleportResult": {"Success": 0, "Failure": 1},
    "PreferredInput": {"KeyboardAndMouse": 0, "Gamepad": 1, "Touch": 2},
}


def enum_item_names(enum):
    return ENUMS.get(enum, {})
